/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.form;

import domain.Menadzer;
import ui.form.gf.GlavnaForma;
import java.util.logging.Level;
import java.util.logging.Logger;
import ui.controller.Kontroller;
import ui.form.ugovor.UgovorForma;

/**
 *
 * @author Marko
 */
public class PocetnaForma extends javax.swing.JFrame {
    private Menadzer ulogovaniMenadzer;
    /**
     * Creates new form PocetnaForma
     */
    public PocetnaForma() {
        initComponents();
        setSize(475, 355);
        setLocationRelativeTo(null);
    }

    public Menadzer getUlogovaniMenadzer() {
        return ulogovaniMenadzer;
    }

    public void setUlogovaniMenadzer(Menadzer ulogovaniMenadzer) {
        this.ulogovaniMenadzer = ulogovaniMenadzer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonOdjaviSe = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemGlavnaForma = new javax.swing.JMenuItem();
        jMenuItemUgovori = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jLabel1.setText("jLabel1");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nikola\\Desktop\\Seminarski\\Jordan.jpg")); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nikola\\Desktop\\Seminarski\\Jordan.jpg")); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nikola\\Desktop\\Seminarski\\Jordan.jpg")); // NOI18N
        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonOdjaviSe.setText("Odjavi se");
        jButtonOdjaviSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdjaviSeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOdjaviSe);
        jButtonOdjaviSe.setBounds(350, 240, 80, 22);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nikola\\Desktop\\Seminarski\\Jordan.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-60, -10, 610, 320);

        jMenu2.setText("Meni");
        jMenu2.setMaximumSize(new java.awt.Dimension(100, 32767));
        jMenu2.setMinimumSize(new java.awt.Dimension(50, 20));

        jMenuItemGlavnaForma.setText("Glavna Forma");
        jMenuItemGlavnaForma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemGlavnaFormaMouseClicked(evt);
            }
        });
        jMenuItemGlavnaForma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGlavnaFormaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemGlavnaForma);

        jMenuItemUgovori.setText("Rad sa ugovorima");
        jMenuItemUgovori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUgovoriActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemUgovori);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemGlavnaFormaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemGlavnaFormaMouseClicked

    }//GEN-LAST:event_jMenuItemGlavnaFormaMouseClicked

    private void jMenuItemGlavnaFormaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGlavnaFormaActionPerformed
        try {
            GlavnaForma gf = new GlavnaForma();
            gf.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(PocetnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemGlavnaFormaActionPerformed

    private void jButtonOdjaviSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdjaviSeActionPerformed
        try {
            Kontroller.getInstance().odjaviSe(ulogovaniMenadzer);
            this.dispose();
            LoginForma lf = new LoginForma();
            lf.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(PocetnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonOdjaviSeActionPerformed

    private void jMenuItemUgovoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUgovoriActionPerformed
        try {
            UgovorForma uf = new UgovorForma();
            uf.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(PocetnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemUgovoriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PocetnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PocetnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PocetnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PocetnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PocetnaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOdjaviSe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItemGlavnaForma;
    private javax.swing.JMenuItem jMenuItemUgovori;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
