/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.form.ugovor;

import domain.Igrac;
import domain.Klub;
import domain.StavkaUgovora;
import domain.Ugovor;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import table.models.ModelTabeleStavkaUgovora;
import ui.controller.Kontroller;

/**
 *
 * @author Marko
 */
public class ObicanTransferForma extends javax.swing.JFrame {

    private ModelTabeleStavkaUgovora mtsu;
    private List<StavkaUgovora> stavkeUgovora = new ArrayList<>();
    private UgovorForma uf;

    /**
     * Creates new form ObicanTransferForma
     */
    public ObicanTransferForma() throws Exception {
        initComponents();
        popuniComboBoxIgracima();
        popuniComboBoxeveKlubovima();
        postaviModelTabeleStavkaUgovora();
        setLocationRelativeTo(null);

    }

    public UgovorForma getUf() {
        return uf;
    }

    public void setUf(UgovorForma uf) {
        this.uf = uf;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxIgraci = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxNapusteniKlubovi = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStavkeUgovora = new javax.swing.JTable();
        jButtonDodajStavku = new javax.swing.JButton();
        jButtonObrisiStavku = new javax.swing.JButton();
        jButtonZapamti = new javax.swing.JButton();
        jButtonZavrsiRad = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxPridruzeniKlubovi = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Odaberite igraca:");

        jLabel2.setText("Odaberite klub:");

        jComboBoxNapusteniKlubovi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNapusteniKluboviActionPerformed(evt);
            }
        });

        jTableStavkeUgovora.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jTableStavkeUgovora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableStavkeUgovoraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableStavkeUgovora);

        jButtonDodajStavku.setText("Dodaj stavku");
        jButtonDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajStavkuActionPerformed(evt);
            }
        });

        jButtonObrisiStavku.setText("Obrisi stavku");
        jButtonObrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiStavkuActionPerformed(evt);
            }
        });

        jButtonZapamti.setText("Zapamti");
        jButtonZapamti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZapamtiActionPerformed(evt);
            }
        });

        jButtonZavrsiRad.setText("Zavrsi rad");
        jButtonZavrsiRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZavrsiRadActionPerformed(evt);
            }
        });

        jLabel3.setText("Odaberite klub:");

        jLabel4.setText("---------->");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jComboBoxIgraci, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(jButtonZapamti)
                                .addGap(185, 185, 185)
                                .addComponent(jButtonZavrsiRad))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonDodajStavku)
                                    .addComponent(jButtonObrisiStavku)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxNapusteniKlubovi, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(22, 22, 22)
                                .addComponent(jComboBoxPridruzeniKlubovi, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxIgraci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonDodajStavku)
                        .addGap(30, 30, 30)
                        .addComponent(jButtonObrisiStavku)
                        .addGap(72, 72, 72)
                        .addComponent(jButtonZavrsiRad)
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxNapusteniKlubovi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxPridruzeniKlubovi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButtonZapamti)
                        .addGap(37, 37, 37))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajStavkuActionPerformed
        StavkaUgovora stavkaUgovora = new StavkaUgovora();
        mtsu.dodajStavku(stavkaUgovora);
    }//GEN-LAST:event_jButtonDodajStavkuActionPerformed

    private void jTableStavkeUgovoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableStavkeUgovoraMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableStavkeUgovoraMouseClicked

    private void jButtonObrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiStavkuActionPerformed
        int selektovaniRed = jTableStavkeUgovora.getSelectedRow();
        if (selektovaniRed == -1) {
            JOptionPane.showMessageDialog(this, "Niste izabrali stavku ugovora!", "Upozorenje", JOptionPane.WARNING_MESSAGE);
            return;
        }
        mtsu.obrisiStavku(selektovaniRed);
    }//GEN-LAST:event_jButtonObrisiStavkuActionPerformed

    private void jButtonZapamtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZapamtiActionPerformed
        try {
            String warningString = "";
            stavkeUgovora = mtsu.getStavkeUgovora();
            Igrac igrac = (Igrac) jComboBoxIgraci.getSelectedItem();
            if (igrac == null) {
                warningString += "Igrac mora biti izabran!" + "\n";
            }
            Object odlazeciKlub = jComboBoxNapusteniKlubovi.getSelectedItem();
            if (odlazeciKlub == null) {
                warningString += "Napusteni klub mora biti izabran!" + "\n";
            }
            Object dolazeciKlub = jComboBoxPridruzeniKlubovi.getSelectedItem();
            if (dolazeciKlub == null) {
                warningString += "Pridruzeni klub mora biti izabran!" + "\n";
            }
            if (igrac == null || odlazeciKlub == null || dolazeciKlub == null) {
                JOptionPane.showMessageDialog(this, warningString, "Upozorenje", JOptionPane.WARNING_MESSAGE);
                return;
            }
            Klub napusteniKlub;
            Klub pridruzeniKlub;
            if (odlazeciKlub.equals("--Slobodan igrac--")) {
                napusteniKlub = new Klub();
                napusteniKlub.setNaziv("--Slobodan igrac--");
            } else {
                napusteniKlub = (Klub) odlazeciKlub;
            }
            if (dolazeciKlub.equals("--Slobodan igrac--")) {
                pridruzeniKlub = new Klub();
                pridruzeniKlub.setNaziv("--Slobodan igrac--");
            } else {
                pridruzeniKlub = (Klub) dolazeciKlub;
            }
            Ugovor ugovor = new Ugovor(-1, igrac, napusteniKlub, pridruzeniKlub, stavkeUgovora);
            Kontroller.getInstance().zapamtiUgovor(ugovor);
            uf.postaviKoloneTabeleUgovor();
            uf.postaviUkupanBrojUgovora();
            isprazniPolja();
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio ugovor!", "Potvrda", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti ugovor!" /*+ ex.getMessage()*/, "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonZapamtiActionPerformed

    private void jButtonZavrsiRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZavrsiRadActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonZavrsiRadActionPerformed

    private void jComboBoxNapusteniKluboviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNapusteniKluboviActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxNapusteniKluboviActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ObicanTransferForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ObicanTransferForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ObicanTransferForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ObicanTransferForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ObicanTransferForma().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(ObicanTransferForma.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajStavku;
    private javax.swing.JButton jButtonObrisiStavku;
    private javax.swing.JButton jButtonZapamti;
    private javax.swing.JButton jButtonZavrsiRad;
    private javax.swing.JComboBox<Object> jComboBoxIgraci;
    private javax.swing.JComboBox<Object> jComboBoxNapusteniKlubovi;
    private javax.swing.JComboBox<Object> jComboBoxPridruzeniKlubovi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableStavkeUgovora;
    // End of variables declaration//GEN-END:variables

    private void popuniComboBoxIgracima() throws Exception {
        List<Igrac> igraci = Kontroller.getInstance().ucitajListuIgraca();
        Collections.sort(igraci);
        jComboBoxIgraci.setModel(new DefaultComboBoxModel<>(igraci.toArray()));
        jComboBoxIgraci.setSelectedItem(null);
    }

    private void popuniComboBoxeveKlubovima() throws Exception {
        List<Klub> klubovi = Kontroller.getInstance().ucitajListuKlubova();
        Collections.sort(klubovi);
        jComboBoxNapusteniKlubovi.setModel(new DefaultComboBoxModel<>(klubovi.toArray()));
        jComboBoxNapusteniKlubovi.addItem("--Slobodan igrac--");
        jComboBoxNapusteniKlubovi.setSelectedItem(null);
        jComboBoxPridruzeniKlubovi.setModel(new DefaultComboBoxModel<>(klubovi.toArray()));
        jComboBoxPridruzeniKlubovi.addItem("--Slobodan igrac--");
        jComboBoxPridruzeniKlubovi.setSelectedItem(null);
    }

    private void postaviModelTabeleStavkaUgovora() {
        mtsu = new ModelTabeleStavkaUgovora(stavkeUgovora);
        mtsu.setOtf(this);
        jTableStavkeUgovora.setModel(mtsu);
        jTableStavkeUgovora.getColumnModel().getColumn(0).setPreferredWidth(10);
    }

    public void prikaziUpozorenje(String warningString) {
        JOptionPane.showMessageDialog(this, warningString, "Upozorenje", JOptionPane.WARNING_MESSAGE);
    }

    private void isprazniPolja() {
        jComboBoxIgraci.setSelectedItem(null);
        jComboBoxNapusteniKlubovi.setSelectedItem(null);
        jComboBoxPridruzeniKlubovi.setSelectedItem(null);
        stavkeUgovora = new ArrayList<>();
        postaviModelTabeleStavkaUgovora();
    }

}
